// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLAFCxipThML68Trp3I7FNE5PumDB0x0',
    appId: '1:1065364705626:web:953ab9e44d8128b90aa363',
    messagingSenderId: '1065364705626',
    projectId: 'kit721-dongyig',
    authDomain: 'kit721-dongyig.firebaseapp.com',
    storageBucket: 'kit721-dongyig.firebasestorage.app',
    measurementId: 'G-YC5RW91S12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDjzDr5Gz_aV5nRLiFAMnsLQPBE6dqIPE',
    appId: '1:1065364705626:android:ea9f71f79c5c56090aa363',
    messagingSenderId: '1065364705626',
    projectId: 'kit721-dongyig',
    storageBucket: 'kit721-dongyig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxLbGFw_Ps_ARPoazNK6W968CbTMf76o',
    appId: '1:1065364705626:ios:57c3e4ef81a8ffaa0aa363',
    messagingSenderId: '1065364705626',
    projectId: 'kit721-dongyig',
    storageBucket: 'kit721-dongyig.firebasestorage.app',
    iosBundleId: 'com.example.tutorial13',
  );
}
